/**
 * REXTON demo dataset.
 *
 *   npm run db:seed
 *
 * Idempotent â€” wipes and recreates every seeded table. All imagery is
 * original SVG artwork generated by scripts/generate-placeholders.mjs.
 */
import "dotenv/config";
import { db } from "../lib/db";
import bcrypt from "bcryptjs";

const IMG = {
  onyx: "/images/products/watch-onyx.svg",
  silver: "/images/products/watch-silver.svg",
  champagne: "/images/products/watch-champagne.svg",
  midnight: "/images/products/watch-midnight.svg",
  ivory: "/images/products/watch-ivory.svg",
  slate: "/images/products/watch-slate.svg",
};

/** Minor units â€” â‚¹12,900 â†’ 1290000 */
const rupees = (value: number) => value * 100;

const daysAgo = (days: number, hour = 11) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 24, 0, 0);
  return d;
};

async function main() {
  console.log("Seeding REXTONâ€¦");

  // â”€â”€ Reset â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const tables = [
    "AuditLog",
    "Notification",
    "InventoryTransaction",
    "Inventory",
    "CouponUsage",
    "CouponProduct",
    "CouponCategory",
    "Coupon",
    "Review",
    "Invoice",
    "Shipment",
    "Refund",
    "Payment",
    "OrderItem",
    "Order",
    "WishlistItem",
    "Wishlist",
    "CartItem",
    "Cart",
    "ProductImage",
    "ProductVariant",
    "Product",
    "Category",
    "Collection",
    "BlogPost",
    "BlogCategory",
    "Banner",
    "NewsletterSubscriber",
    "ContactMessage",
    "SiteSetting",
    "PasswordReset",
    "Session",
    "Address",
    "User",
  ] as const;

  for (const table of tables) {
    await (
      db as unknown as Record<
        string,
        { deleteMany: () => Promise<unknown> }
      >
    )[table].deleteMany();
  }

  // â”€â”€ Users â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const staffPassword = await bcrypt.hash("Rexton@2026", 12);
  const customerPassword = await bcrypt.hash("Customer@2026", 12);

  const admin = await db.user.create({
    data: {
      name: "Rexton Admin",
      email: "admin@rexton.in",
      phone: "9876500001",
      passwordHash: staffPassword,
      role: "SUPER_ADMIN",
      emailVerifiedAt: new Date(),
    },
  });

  const manager = await db.user.create({
    data: {
      name: "Store Manager",
      email: "manager@rexton.in",
      phone: "9876500002",
      passwordHash: staffPassword,
      role: "ADMIN",
      emailVerifiedAt: new Date(),
    },
  });

  await db.user.create({
    data: {
      name: "Catalogue Editor",
      email: "editor@rexton.in",
      passwordHash: staffPassword,
      role: "STAFF",
      emailVerifiedAt: new Date(),
    },
  });

  const customerSeed = [
    { name: "Aarav Sharma", email: "aarav.sharma@example.in", phone: "9812340001" },
    { name: "Priya Nair", email: "priya.nair@example.in", phone: "9812340002" },
    { name: "Rohan Mehta", email: "rohan.mehta@example.in", phone: "9812340003" },
    { name: "Ananya Iyer", email: "ananya.iyer@example.in", phone: "9812340004" },
    { name: "Kabir Singh", email: "kabir.singh@example.in", phone: "9812340005" },
  ];

  const customers = [];
  for (const seed of customerSeed) {
    customers.push(
      await db.user.create({
        data: {
          ...seed,
          passwordHash: customerPassword,
          role: "CUSTOMER",
          emailVerifiedAt: new Date(),
        },
      })
    );
  }

  const [aarav, priya, rohan, ananya, kabir] = customers;

  const addresses = [
    {
      user: aarav,
      fullName: "Aarav Sharma",
      phone: "9812340001",
      line1: "14 Lodhi Estate",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110003",
    },
    {
      user: priya,
      fullName: "Priya Nair",
      phone: "9812340002",
      line1: "221 Marine Drive",
      line2: "Flat 7B",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400020",
    },
    {
      user: rohan,
      fullName: "Rohan Mehta",
      phone: "9812340003",
      line1: "8 Lavelle Road",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560001",
    },
  ];

  for (const [index, address] of addresses.entries()) {
    const { user, ...fields } = address;
    await db.address.create({
      data: {
        ...fields,
        userId: user.id,
        email: user.email,
        isDefaultShipping: true,
        isDefaultBilling: index === 0,
      },
    });
  }

  // â”€â”€ Catalogue â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const categories = await Promise.all(
    [
      { name: "Classic", slug: "classic", description: "Quiet dials, timeless proportion.", sortOrder: 1 },
      { name: "Chronograph", slug: "chronograph", description: "Complications built for measurement.", sortOrder: 2 },
      { name: "Automatic", slug: "automatic", description: "Self-winding movements, no battery.", sortOrder: 3 },
      { name: "Minimal", slug: "minimal", description: "Stripped to essentials.", sortOrder: 4 },
    ].map((data) => db.category.create({ data }))
  );

  const collections = await Promise.all(
    [
      {
        name: "Heritage",
        slug: "heritage",
        description: "REXTON roots â€” the shapes that defined the house.",
        sortOrder: 1,
      },
      {
        name: "Atelier",
        slug: "atelier",
        description: "Small-batch finishing, hand-regulated movements.",
        sortOrder: 2,
      },
      {
        name: "Sport",
        slug: "sport",
        description: "Higher water resistance, harder-wearing straps.",
        sortOrder: 3,
      },
      {
        name: "Limited Edition",
        slug: "limited-edition",
        description: "Numbered runs. Never repeated.",
        sortOrder: 4,
      },
    ].map((data) => db.collection.create({ data }))
  );

  const [classic, chronograph, automatic, minimal] = categories;
  const [heritage, atelier, sport, limited] = collections;

  interface ProductSeed {
    name: string;
    slug: string;
    sku: string;
    price: number;
    compareAt?: number;
    category: typeof classic;
    collection: typeof heritage;
    image: string;
    short: string;
    description: string;
    movement: "QUARTZ" | "AUTOMATIC" | "MECHANICAL" | "SKELETON";
    dial: string;
    strap: string;
    material: string;
    gender: "MEN" | "WOMEN" | "UNISEX";
    stock: number;
    featured?: boolean;
    bestSeller?: boolean;
    newArrival?: boolean;
    limited?: boolean;
    tags: string;
  }

  const productSeeds: ProductSeed[] = [
    {
      name: "REXTON Heritage 38",
      slug: "rexton-heritage-38",
      sku: "RX-HER-38-SLV",
      price: 18900,
      compareAt: 22500,
      category: classic,
      collection: heritage,
      image: IMG.silver,
      short: "A 38mm three-hand automatic with a sunburst silver dial.",
      description:
        "The Heritage 38 is the reference point for everything REXTON makes: a balanced 38mm case, a sunray dial that shifts with the light, and an automatic movement visible through the caseback. Sized for wrists that prefer quiet confidence over presence.",
      movement: "AUTOMATIC",
      dial: "Silver",
      strap: "Stainless steel bracelet",
      material: "316L stainless steel",
      gender: "UNISEX",
      stock: 24,
      featured: true,
      bestSeller: true,
      tags: "heritage,automatic,everyday,silver",
    },
    {
      name: "REXTON Chronograph No. 7",
      slug: "rexton-chronograph-no-7",
      sku: "RX-CHR-07-BLK",
      price: 27500,
      compareAt: 32000,
      category: chronograph,
      collection: heritage,
      image: IMG.onyx,
      short: "Column-wheel chronograph with a matte onyx dial.",
      description:
        "Seven iterations in, the Chronograph No. 7 is the one we keep coming back to. Two recessed counters, a crisp 60-second scale, and a pusher action tuned to feel mechanical rather than merely clicky.",
      movement: "QUARTZ",
      dial: "Onyx black",
      strap: "Full-grain leather",
      material: "316L stainless steel",
      gender: "MEN",
      stock: 18,
      featured: true,
      bestSeller: true,
      tags: "chronograph,black,leather,racing",
    },
    {
      name: "REXTON Atelier Rose Gold",
      slug: "rexton-atelier-rose-gold",
      sku: "RX-ATL-RG-34",
      price: 34500,
      compareAt: 39000,
      category: automatic,
      collection: atelier,
      image: IMG.champagne,
      short: "34mm rose-gold PVD case, champagne dial, hand-finished.",
      description:
        "Finished in our atelier over three days, the Rose Gold carries a champagne dial with applied indices and a hand-regulated movement. Limited to the pieces our finishers can complete without hurrying.",
      movement: "AUTOMATIC",
      dial: "Champagne",
      strap: "Satin leather",
      material: "Rose gold PVD steel",
      gender: "WOMEN",
      stock: 9,
      featured: true,
      newArrival: true,
      tags: "atelier,rose gold,automatic,dress",
    },
    {
      name: "REXTON Meridian Automatic",
      slug: "rexton-meridian-automatic",
      sku: "RX-MER-AUT-40",
      price: 24900,
      category: automatic,
      collection: atelier,
      image: IMG.midnight,
      short: "40mm midnight-blue automatic with a display caseback.",
      description:
        "The Meridian pairs a deep midnight dial with a sapphire display back, so the rotor is always on show. A day-to-night piece with 100m of water resistance behind it.",
      movement: "AUTOMATIC",
      dial: "Midnight blue",
      strap: "Stainless steel bracelet",
      material: "316L stainless steel",
      gender: "MEN",
      stock: 31,
      bestSeller: true,
      tags: "automatic,blue,steel,office",
    },
    {
      name: "REXTON Meridian 40 Slate",
      slug: "rexton-meridian-40-slate",
      sku: "RX-MER-SLT-40",
      price: 23900,
      compareAt: 26900,
      category: automatic,
      collection: heritage,
      image: IMG.slate,
      short: "Slate-grey dial, brushed case, 100m water resistance.",
      description:
        "The slate Meridian trades shine for texture: a vertically brushed dial, a bead-blasted case flank, and a bracelet that disappears under a cuff.",
      movement: "AUTOMATIC",
      dial: "Slate grey",
      strap: "Stainless steel bracelet",
      material: "316L stainless steel",
      gender: "UNISEX",
      stock: 4,
      tags: "automatic,grey,steel,tool watch",
    },
    {
      name: "REXTON Minimal 36",
      slug: "rexton-minimal-36",
      sku: "RX-MIN-36-IVY",
      price: 12900,
      category: minimal,
      collection: heritage,
      image: IMG.ivory,
      short: "No complications. Just time, clearly told.",
      description:
        "Two hands of visual weight, an ivory dial and a slim 7.8mm case. The Minimal 36 removes everything that does not help you read the time.",
      movement: "QUARTZ",
      dial: "Ivory",
      strap: "Italian leather",
      material: "316L stainless steel",
      gender: "UNISEX",
      stock: 42,
      featured: true,
      tags: "minimal,ivory,slim,everyday",
    },
    {
      name: "REXTON Minimal 36 Onyx",
      slug: "rexton-minimal-36-onyx",
      sku: "RX-MIN-36-ONX",
      price: 12900,
      category: minimal,
      collection: heritage,
      image: IMG.onyx,
      short: "The Minimal in onyx, on a black leather strap.",
      description:
        "Same 36mm case and uncluttered dial as the ivory version, executed in deep onyx with polished indices.",
      movement: "QUARTZ",
      dial: "Onyx black",
      strap: "Black leather",
      material: "316L stainless steel",
      gender: "UNISEX",
      stock: 0,
      tags: "minimal,black,leather",
    },
    {
      name: "REXTON Regatta Sport",
      slug: "rexton-regatta-sport",
      sku: "RX-SPT-RGT-42",
      price: 21500,
      compareAt: 24500,
      category: chronograph,
      collection: sport,
      image: IMG.silver,
      short: "200m diver-style chronograph with a ceramic bezel.",
      description:
        "Built for water: a unidirectional ceramic bezel, screw-down crown and 200m rating. The Regatta keeps its chronograph useful on land without pretending to be a desk diver.",
      movement: "QUARTZ",
      dial: "Silver",
      strap: "Rubidium rubber strap",
      material: "316L stainless steel",
      gender: "MEN",
      stock: 15,
      tags: "sport,diver,chronograph,200m",
    },
    {
      name: "REXTON Aero Chronograph",
      slug: "rexton-aero-chronograph",
      sku: "RX-CHR-AER-41",
      price: 29900,
      category: chronograph,
      collection: sport,
      image: IMG.slate,
      short: "Pilot-inspired panda dial with a leather racing strap.",
      description:
        "High-contrast sub-dials, oversized crown and a 41mm case built to be read at a glance. The Aero is our nod to cockpit instruments.",
      movement: "MECHANICAL",
      dial: "Slate / panda",
      strap: "Perforated leather",
      material: "316L stainless steel",
      gender: "MEN",
      stock: 7,
      newArrival: true,
      tags: "chronograph,pilot,panda,racing",
    },
    {
      name: "REXTON Nocturne Skeleton",
      slug: "rexton-nocturne-skeleton",
      sku: "RX-SKL-NOC-40",
      price: 46500,
      compareAt: 52000,
      category: automatic,
      collection: atelier,
      image: IMG.onyx,
      short: "Open-worked dial, 42-hour reserve, sapphire front and back.",
      description:
        "Every bridge is skeletonised and every edge bevelled by hand. The Nocturne is the most demanding piece we make, and the reason we keep our atelier small.",
      movement: "SKELETON",
      dial: "Open-worked",
      strap: "Alligator-grain leather",
      material: "316L stainless steel",
      gender: "UNISEX",
      stock: 3,
      featured: true,
      tags: "skeleton,atelier,mechanical,collector",
    },
    {
      name: "REXTON Solstice No. 1",
      slug: "rexton-solstice-no-1",
      sku: "RX-LTD-SOL-001",
      price: 58000,
      category: classic,
      collection: limited,
      image: IMG.champagne,
      short: "Numbered to 250 pieces. Champagne dial, gold-plated hands.",
      description:
        "The first limited release from REXTON: 250 numbered pieces, each with a champagne dial, gold-plated hands and a certificate of authenticity recorded against your account.",
      movement: "AUTOMATIC",
      dial: "Champagne",
      strap: "Hand-stitched leather",
      material: "Gold-plated steel",
      gender: "UNISEX",
      stock: 2,
      limited: true,
      newArrival: true,
      tags: "limited,numbered,collector,gold",
    },
    {
      name: "REXTON Cadence GMT",
      slug: "rexton-cadence-gmt",
      sku: "RX-GMT-CDN-40",
      price: 32500,
      category: classic,
      collection: limited,
      image: IMG.midnight,
      short: "Independent 24-hour hand for a second time zone.",
      description:
        "A true GMT complication with an independently adjustable 24-hour hand, so setting the local time never disturbs your home zone. Produced in a run of 400.",
      movement: "AUTOMATIC",
      dial: "Midnight blue",
      strap: "Stainless steel bracelet",
      material: "316L stainless steel",
      gender: "MEN",
      stock: 11,
      limited: true,
      tags: "gmt,travel,limited,blue",
    },
  ];

  const products: Array<{
    id: string;
    name: string;
    sku: string;
    price: number;
  }> = [];
  for (const seed of productSeeds) {
    const {
      category,
      collection,
      image,
      price,
      compareAt,
      stock,
      short,
      featured,
      bestSeller,
      newArrival,
      limited,
      ...rest
    } = seed;

    const product = await db.product.create({
      data: {
        name: rest.name,
        slug: rest.slug,
        sku: rest.sku,
        description: rest.description,
        shortDescription: short,
        tags: rest.tags,
        price: rupees(price),
        compareAtPrice: compareAt ? rupees(compareAt) : null,
        categoryId: category.id,
        collectionId: collection.id,
        material: rest.material,
        dialColor: rest.dial,
        strapMaterial: rest.strap,
        strapColor: rest.strap,
        caseMaterial: rest.material,
        caseDiameter: "40 mm",
        caseThickness: "10.8 mm",
        movement: rest.movement,
        gender: rest.gender,
        waterResistance:
          collection.slug === "sport" ? "200 m" : "100 m",
        glassType: "Sapphire crystal",
        warranty: "2 year international warranty",
        stock,
        isFeatured: Boolean(featured),
        isBestSeller: Boolean(bestSeller),
        isNewArrival: Boolean(newArrival),
        isLimitedEdition: Boolean(limited),
        seoTitle: `${rest.name} Â· REXTON Watches`,
        seoDescription: short,
        images: {
          create: [
            { url: image, alt: `${seed.name} front view`, position: 0 },
            {
              url: image,
              alt: `${seed.name} detail`,
              position: 1,
            },
          ],
        },
        inventory: {
          create: {
            quantity: stock,
            lowStockThreshold: 5,
          },
        },
      },
    });

    await db.inventoryTransaction.create({
      data: {
        productId: product.id,
        change: stock,
        type: "INITIAL_STOCK",
        note: "Seed inventory",
      },
    });

    products.push(product);
  }

  // â”€â”€ Coupons â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const coupons = await Promise.all([
    db.coupon.create({
      data: {
        code: "WELCOME10",
        description: "10% off your first REXTON order",
        discountType: "PERCENTAGE",
        value: 1000,
        minOrderAmount: rupees(5000),
        maxDiscount: rupees(3000),
        usageLimit: 500,
        perUserLimit: 1,
        endsAt: daysAgo(-120),
      },
    }),
    db.coupon.create({
      data: {
        code: "FLAT500",
        description: "â‚¹500 off any order above â‚¹10,000",
        discountType: "FIXED",
        value: rupees(500),
        minOrderAmount: rupees(10000),
        usageLimit: 200,
        perUserLimit: 2,
        endsAt: daysAgo(-60),
      },
    }),
    db.coupon.create({
      data: {
        code: "ATELIER15",
        description: "15% off Atelier collection pieces",
        discountType: "PERCENTAGE",
        value: 1500,
        minOrderAmount: rupees(20000),
        maxDiscount: rupees(6000),
        usageLimit: 100,
        perUserLimit: 1,
        isActive: false,
      },
    }),
  ]);

  // â”€â”€ Orders â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const orderPlan = [
    { customer: aarav, items: [0, 5], status: "DELIVERED", pay: "PAID", days: 46 },
    { customer: priya, items: [2], status: "DELIVERED", pay: "PAID", days: 38 },
    { customer: rohan, items: [3, 6], status: "DELIVERED", pay: "PAID", days: 30 },
    { customer: ananya, items: [5], status: "DELIVERED", pay: "PAID", days: 24 },
    { customer: kabir, items: [1, 7], status: "SHIPPED", pay: "PAID", days: 14 },
    { customer: aarav, items: [3], status: "OUT_FOR_DELIVERY", pay: "PAID", days: 9 },
    { customer: priya, items: [9], status: "PROCESSING", pay: "PAID", days: 5 },
    { customer: null, items: [4], status: "CONFIRMED", pay: "PENDING_PAYMENT", days: 3 },
    { customer: rohan, items: [8], status: "CANCELLED", pay: "CANCELLED", days: 20 },
    { customer: ananya, items: [11], status: "REFUNDED", pay: "REFUNDED", days: 60 },
  ];

  const orderRecords = [];
  let orderSeq = 1;

  for (const plan of orderPlan) {
    const items = plan.items.map((index) => ({
      product: products[index],
      imageUrl: productSeeds[index].image,
    }));
    const subtotal = items.reduce(
      (sum, entry) => sum + entry.product.price,
      0
    );
    const discount = 0;
    const tax = Math.round(subtotal * 0.18);
    const shipping = subtotal > rupees(5000) ? 0 : rupees(200);
    const total = subtotal + tax + shipping - discount;
    const placedAt = daysAgo(plan.days);

    const shippingAddress = JSON.stringify(
      plan.customer
        ? {
            fullName: plan.customer.name,
            phone: plan.customer.phone ?? "",
            line1: "12 Residency Road",
            city: "Bengaluru",
            state: "Karnataka",
            pincode: "560025",
            country: "IN",
          }
        : {
            fullName: "Guest Checkout",
            phone: "9000000000",
            line1: "5 Market Street",
            city: "Pune",
            state: "Maharashtra",
            pincode: "411001",
            country: "IN",
          }
    );

    const order = await db.order.create({
      data: {
        orderNumber: `RX-2026-${String(orderSeq).padStart(4, "0")}`,
        userId: plan.customer?.id,
        customerEmail: plan.customer?.email ?? "guest@example.in",
        customerName: plan.customer?.name ?? "Guest Checkout",
        customerPhone: plan.customer?.phone ?? "9000000000",
        subtotal,
        discount,
        tax,
        shipping,
        total,
        paymentStatus: plan.pay as never,
        status: plan.status as never,
        shippingAddress,
        billingAddress: shippingAddress,
        couponCode: orderSeq % 4 === 0 ? "WELCOME10" : null,
        placedAt,
        createdAt: placedAt,
        paidAt: plan.pay === "PAID" ? placedAt : null,
        shippedAt: ["SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED"].includes(
          plan.status
        )
          ? new Date(placedAt.getTime() + 2 * 86400000)
          : null,
        deliveredAt:
          plan.status === "DELIVERED"
            ? new Date(placedAt.getTime() + 5 * 86400000)
            : null,
        items: {
          create: items.map(({ product, imageUrl }) => ({
            productId: product.id,
            name: product.name,
            sku: product.sku,
            imageUrl,
            price: product.price,
            quantity: 1,
            total: product.price,
          })),
        },
      },
      include: { items: true },
    });

    orderRecords.push(order);

    if (["PAID", "REFUNDED"].includes(plan.pay)) {
      await db.payment.create({
        data: {
          orderId: order.id,
          provider: "MOCK",
          providerOrderId: `order_seed_${orderSeq}`,
          providerPaymentId:
            plan.pay === "PAID" ? `pay_seed_${orderSeq}` : null,
          amount: total,
          status: plan.pay as never,
          method: ["card", "upi", "netbanking"][orderSeq % 3],
          createdAt: placedAt,
        },
      });

      await db.invoice.create({
        data: {
          orderId: order.id,
          invoiceNumber: `INV-2026-${String(orderSeq).padStart(4, "0")}`,
          subtotal,
          tax,
          discount,
          shipping,
          total,
          issuedAt: placedAt,
        },
      });
    }

    if (order.couponCode) {
      const coupon = coupons.find((c) => c.code === order.couponCode);
      if (coupon) {
        await db.couponUsage.create({
          data: {
            couponId: coupon.id,
            orderId: order.id,
            userId: plan.customer?.id,
            discountAmount: rupees(500),
            createdAt: placedAt,
          },
        });
      }
    }

    if (["SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED"].includes(plan.status)) {
      await db.shipment.create({
        data: {
          orderId: order.id,
          courier: "Blue Dart",
          trackingNumber: `BD${String(70000000 + orderSeq)}`,
          status: plan.status,
          shippedAt: new Date(placedAt.getTime() + 2 * 86400000),
          deliveredAt:
            plan.status === "DELIVERED"
              ? new Date(placedAt.getTime() + 5 * 86400000)
              : null,
          estimatedDeliveryAt: new Date(placedAt.getTime() + 7 * 86400000),
        },
      });
    }

    if (plan.pay === "REFUNDED") {
      await db.refund.create({
        data: {
          orderId: order.id,
          amount: total,
          status: "COMPLETED",
          reason: "Customer changed their mind within the return window",
          providerRefundId: `rfnd_seed_${orderSeq}`,
          createdAt: placedAt,
        },
      });
    }

    orderSeq += 1;
  }

  // â”€â”€ Reviews â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const reviewSeeds = [
    { p: 0, u: aarav, rating: 5, title: "Exactly what I wanted", body: "Proportions are perfect on a 6.75\" wrist. The silver dial changes completely depending on the light.", status: "APPROVED" },
    { p: 1, u: rohan, rating: 5, title: "Pushers feel genuinely mechanical", body: "I have owned chronographs twice the price that do not reset as crisply as this one.", status: "APPROVED" },
    { p: 3, u: priya, rating: 4, title: "Excellent daily wearer", body: "Slips under a shirt cuff easily and the bracelet has not scratched in three weeks of wear.", status: "APPROVED" },
    { p: 5, u: ananya, rating: 5, title: "Beautifully minimal", body: "No date, no clutter. It tells the time and nothing else, which is exactly the point.", status: "APPROVED" },
    { p: 6, u: kabir, rating: 3, title: "Waiting on a restock", body: "Liked the design enough to order the ivory version after the onyx sold out.", status: "APPROVED" },
    { p: 9, u: aarav, rating: 5, title: "Worth the wait", body: "The skeletonisation is finished properly â€” no rough edges anywhere under a loupe.", status: "APPROVED" },
    { p: 7, u: rohan, rating: 4, title: "Solid diver", body: "Bezel action is firm with almost no back-play. Rubber strap is softer than expected.", status: "APPROVED" },
    { p: 11, u: priya, rating: 5, title: "The GMT actually works", body: "Set three zones in under a minute. The 24h hand moves independently like it should.", status: "APPROVED" },
    { p: 2, u: ananya, rating: 4, title: "Gorgeous but dressy", body: "More delicate than the photos suggest. Beautiful for evenings.", status: "PENDING" },
    { p: 8, u: kabir, rating: 2, title: "Strap arrived creased", body: "The watch is fine but the strap had a fold mark out of the box. Support is sorting it.", status: "PENDING" },
    { p: 4, u: rohan, rating: 1, title: "Promotional post", body: "Buy my discount watches at example-dot-com!", status: "REJECTED" },
  ];

  for (const seed of reviewSeeds) {
    const product = products[seed.p];
    await db.review.create({
      data: {
        productId: product.id,
        userId: seed.u.id,
        rating: seed.rating,
        title: seed.title,
        body: seed.body,
        status: seed.status as never,
        isVerifiedPurchase: true,
        isFeatured: seed.rating === 5 && seed.status === "APPROVED",
        createdAt: daysAgo(Math.floor(Math.random() * 40) + 5),
      },
    });
  }

  // â”€â”€ Wishlist & cart â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  await db.wishlist.create({
    data: {
      userId: priya.id,
      items: {
        create: [
          { productId: products[9].id },
          { productId: products[3].id },
        ],
      },
    },
  });

  await db.cart.create({
    data: {
      userId: aarav.id,
      items: {
        create: [
          {
            productId: products[0].id,
            quantity: 1,
            priceAtAdd: products[0].price,
          },
        ],
      },
    },
  });

  // â”€â”€ Content â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const journal = await db.blogCategory.create({
    data: { name: "Workshop", slug: "workshop" },
  });

  await db.blogPost.create({
    data: {
      title: "How we regulate a movement",
      slug: "how-we-regulate-a-movement",
      excerpt:
        "Five positions, three temperatures, and one tolerance we refuse to widen.",
      coverImage: IMG.silver,
      content:
        "Every REXTON movement is timed in five positions over three temperatures before it is allowed into a case. If it drifts beyond our tolerance, it goes back to the bench â€” there is no second grade.",
      authorId: admin.id,
      categoryId: journal.id,
      tags: "craft,regulation,quality",
      status: "PUBLISHED",
      publishedAt: daysAgo(12),
      seoTitle: "How REXTON regulates a movement",
      seoDescription: "Inside the timing process behind every REXTON watch.",
    },
  });

  await db.blogPost.create({
    data: {
      title: "Building the Solstice No. 1",
      slug: "building-the-solstice-no-1",
      excerpt: "250 numbered pieces and the decisions behind them.",
      coverImage: IMG.champagne,
      content: "Draft â€” the full story of our first limited release.",
      authorId: manager.id,
      categoryId: journal.id,
      tags: "limited edition,solstice",
      status: "DRAFT",
    },
  });

  await db.newsletterSubscriber.createMany({
    data: [
      { email: "aarav.sharma@example.in" },
      { email: "priya.nair@example.in" },
      { email: "collector@example.in" },
    ],
  });

  await db.contactMessage.createMany({
    data: [
      {
        name: "Meera Kapoor",
        email: "meera@example.in",
        subject: "Servicing a 2019 automatic",
        message:
          "Do you service movements purchased outside India? I moved to Singapore last year.",
      },
      {
        name: "Dev Patel",
        email: "dev@example.in",
        subject: "Bulk order enquiry",
        message: "Looking at 12 pieces for a corporate gift. Who should I speak to?",
      },
    ],
  });

  await db.siteSetting.createMany({
    data: [
      { key: "store.name", value: "REXTON WATCHES", group: "brand" },
      { key: "store.tagline", value: "Swiss Timeless Root", group: "brand" },
      { key: "store.email", value: "hello@rexton.in", group: "contact" },
      { key: "store.phone", value: "+91 90000 00000", group: "contact" },
      { key: "shipping.free_threshold", value: String(rupees(5000)), group: "shipping" },
      { key: "shipping.standard_rate", value: String(rupees(200)), group: "shipping" },
      { key: "tax.gst_rate", value: "18", group: "tax" },
      { key: "tax.prices_include_tax", value: "false", group: "tax" },
      { key: "payments.provider", value: "razorpay", group: "payments" },
      { key: "inventory.low_stock_threshold", value: "5", group: "inventory" },
    ],
  });

  await db.banner.create({
    data: {
      title: "Complimentary shipping across India",
      subtitle: "On every order, no minimum",
      position: "HERO",
      isActive: true,
      sortOrder: 0,
    },
  });

  await db.auditLog.create({
    data: {
      actorId: admin.id,
      action: "seed.completed",
      entity: "Database",
      meta: JSON.stringify({
        products: products.length,
        orders: orderRecords.length,
        customers: customers.length,
      }),
    },
  });

  console.log(`
REXTON seeded
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 Products      ${products.length}
 Categories    ${categories.length}
 Collections   ${collections.length}
 Customers     ${customers.length}
 Orders        ${orderRecords.length}
 Reviews       ${reviewSeeds.length}
 Coupons       ${coupons.length}

 Admin    admin@rexton.in   / Rexton@2026
          manager@rexton.in / Rexton@2026
          editor@rexton.in  / Rexton@2026
 Customer aarav.sharma@example.in / Customer@2026
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => db.$disconnect());
